services:
  app:
    image: ${APP_IMAGE}:${APP_VERSION}
    container_name: techhub-app
    environment:
      - NODE_ENV=production
      - SERVER_PORT=${SERVER_PORT}
      - DB_URI=mongodb://${DB_USER}:${DB_PASS}@mongodb:27017/${DB_NAME}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - IMGUR_CLIENT_ID=${IMGUR_CLIENT_ID}
    depends_on:
      - mongodb
    ports:
      - '3000:3000' # host:container
    networks:
      - app_network

  mongodb:
    image: mongo:7.0.14
    container_name: techhub-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - '27017:27017'
    volumes:
      - techhub-db:/data/db # host:container
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro # mount init script
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  techhub-db:
    name: techhub-db
